### ISSUE TITLE
Wrong Network Information - QNAP QXG-10G2T-107

### ISSUE THREAD

**Issue by EVOTk** [turkaysoftware/glow#2]
Hello,

Glow does not show the right information about my QNAP QXG-10G2T-107 network card

Indeed, the MAC address, the name, the driver and the DHCP address is correct but the rest is wrong:

- Connection type is Ethernet 22 not Ethernet 6
- Connection Speed is 10 Gbps(10000Mbps) not 1000Mbps
- Assigned IPv4 is 192.168.100.211, it displays an IPv6 prefix

![image](https://user-images.githubusercontent.com/45015615/232906068-f26ca638-e6b5-4e65-9b23-1d6d1bf6e4e0.png)

Thx

System : 
Windows 10 22H2
Glow 1.62

**Comment by turkaysoftware** [comment]
IPv4 and IPv6 are fixed. It takes shape according to the adapter connected at that moment. So when the adapter is changed from above, the IPv4 and IPv6 fields do not change. The speed issue is processed according to the system reporting. So it is not a Glow-related error. Likewise, Connection Type is a system-induced situation.
